export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const INITIALIZE_PROFILE = 'INITIALIZE_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const UPDATE_STATE = 'UPDATE STATE';
export const ADD_ITINERARY = 'ADD ITINERARY';
