import {generateErrorMessage} from "../../utils/toast";

/**
 * Handle firebase related authentication errors
 * @param toast - chakra ui toast
 * @param code - error code generated by firebase
 */
export const handleErrors = (toast, code) => {
    switch(code) {
        case 'auth/too-many-requests':
            generateErrorMessage(toast, 'Too many login attempts', 'You have attempt many login attempts. Therefore, you are temporarily banned from logging in. Please try again later');
            break;
        case 'auth/wrong-password':
        case 'auth/user-not-found':
            generateErrorMessage(toast, 'Invalid email or password', 'Please check your email and password');
            break;
        case 'auth/email-already-in-use':
            generateErrorMessage(toast, 'Email already exists', 'There is already an account for the email');
            break;
        default:
            console.log(code);
            generateErrorMessage(toast, 'Something went wrong', 'We have encountered an unknown issue. Please contact the system admin');
    }
}
