version: "3.9"

services:
  search:
    build:
      context: ./search_services
    ports:
      - 8000:8000
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  database:
    build:
      context: ./database_services
    ports:
      - 5000:5000
    restart: always

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - search
      - database
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/vol/static

volumes:
  static-data:
